export enum Game_ACTION_TYPES {
  LOADING = "LOADING",
  STOP_LOADING = "STOP_LOADING",
  GAME_ERROR = "GAME_ERROR",
  CLEAN_ERROR = "CLEAN_ERROR",
  SHOW_CARDS = "SHOW_CARDS",
  HIDE_CARDS = "HIDE_CARDS"
}

export enum CARDS_ACTION_TYPES {
  SET_CARDS_PAIRS_COUNT = "SET_CARDS_PAIRS_COUNT",
  SET_CARDS_DATA = "SET_CARDS_DATA",
  GENERATE_CARDS_DATA = "GENERATE_CARDS_DATA",
  SELECT_CARD_BY_ORDER = "SELECT_CARD_BY_ORDER",
  DESELECT_CARDS = "DESELECT_CARDS"
}
