export enum Game_ACTION_TYPES {
  GAME_ERROR = "GAME_ERROR",
  CLEAN_ERROR = "CLEAN_ERROR",
  SHOW_CARDS = "SHOW_CARDS",
  HIDE_CARDS = "HIDE_CARDS",
  RESET_GAME = "RESET_GAME",
  START_GAME_WINNING = "START_GAME_WINNING",
  END_GAME_WINNING = "END_GAME_WINNING",
  RESTART_GAME = "RESTART_GAME",
  GAME_FINISHED = "GAME_FINISHED",
  INITIAL_GAME = "INITIAL_GAME",
  SET_PAIRS_OPTIONS = "SET_PAIRS_OPTIONS",
  RESTART_GAME_BY_OPTION = "RESTART_GAME_BY_OPTION",
  TOGGLE_THEME = "TOGGLE_THEME"
}

export enum CARDS_ACTION_TYPES {
  SET_CARDS_PAIRS_COUNT = "SET_CARDS_PAIRS_COUNT",
  SET_CARDS_DATA = "SET_CARDS_DATA",
  GENERATE_CARDS_DATA = "GENERATE_CARDS_DATA",
  SELECT_CARD_BY_ORDER = "SELECT_CARD_BY_ORDER",
  DESELECT_CARDS = "DESELECT_CARDS"
}

export enum SCORE_ACTION_TYPES {
  INCREMENT_SCORE = "INCREMENT_SCORE",
  INCREMENT_TRIES = "INCREMENT_TRIES"
}
